<?php

use Drupal\Core\Url;

/**
 * @file
 * Contains radix_contact.module.
 */
 
 function get_contactmessages($opt,$fname,$marks) {
	$res = array();
 if($opt == "All"){	
  $results = db_select('radix_contact', 'st')
  ->extend('\Drupal\Core\Database\Query\PagerSelectExtender')
  ->limit(15);
  $results->fields('st');
  $results->orderBy('st.id','DESC');
  $res = $results->execute()->fetchAll();
  $ret = [];
 }else{
	 $results = db_select('radix_contact', 'st')
  ->extend('\Drupal\Core\Database\Query\PagerSelectExtender')
  ->limit(15);
  $results->fields('st');
  $results->orderBy('st.id','DESC');
  $results->condition('fname', $fname);
  $res = $results->execute()->fetchAll();
  $ret = [];
 }
    foreach ($res as $row) {

      $delete = Url::fromUserInput('/admin/structure/radix_contact/radix_contact/delete/' . $row->id, array('attributes' => array('onclick' => "return confirm('Are you Sure')")));
      $edit = Url::fromUserInput('/admin/structure/radix_contact/radix_contact/edit/' . $row->id);
      $edit_link = \Drupal::l('edit', $edit);
      $delete_link = \Drupal::l('delete', $delete);

      $mainLink = t('@linkApprove  @linkReject', array('@linkApprove' => $edit_link, '@linkReject' => $delete_link));
      
      $ret[] = [
        'id' => $row->id,
        'fname' => $row->fname,
		'service_related' => $row->service_related,
		'message' => $row->message,
        'opt' => $mainLink,
      ];
    }
    return $ret;
}